"""add timestamps

Revision ID: 1cd8005f5462
Revises: 1a52ab1be5ab
Create Date: 2026-03-25 00:52:23.738986

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1cd8005f5462'
down_revision: Union[str, Sequence[str], None] = '1a52ab1be5ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('accounts', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('bank_accounts', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('bank_accounts', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('beneficiaries', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('beneficiaries', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('households', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('investment_profiles', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('investment_profiles', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('members', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('members', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('members', 'updated_at')
    op.drop_column('members', 'created_at')
    op.drop_column('investment_profiles', 'updated_at')
    op.drop_column('investment_profiles', 'created_at')
    op.drop_column('households', 'updated_at')
    op.drop_column('beneficiaries', 'updated_at')
    op.drop_column('beneficiaries', 'created_at')
    op.drop_column('bank_accounts', 'updated_at')
    op.drop_column('bank_accounts', 'created_at')
    op.drop_column('accounts', 'updated_at')
    op.drop_column('accounts', 'created_at')
    # ### end Alembic commands ###
