"""add data source

Revision ID: 2adfa47653d6
Revises: 1cd8005f5462
Create Date: 2026-03-25 08:48:47.769980

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2adfa47653d6'
down_revision: Union[str, Sequence[str], None] = '1cd8005f5462'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('account_number', sa.String(length=100), nullable=True))
    op.add_column('accounts', sa.Column('account_value', sa.Float(), nullable=True))
    op.add_column('accounts', sa.Column('ownership', sa.String(length=100), nullable=True))
    op.add_column('accounts', sa.Column('ownership_percentage', sa.Float(), nullable=True))
    op.add_column('bank_accounts', sa.Column('routing_number', sa.String(length=50), nullable=True))
    op.add_column('households', sa.Column('liquid_net_worth', sa.Float(), nullable=True))
    op.add_column('households', sa.Column('expense_range', sa.String(length=100), nullable=True))
    op.add_column('households', sa.Column('risk_tolerance', sa.String(length=50), nullable=True))
    op.add_column('households', sa.Column('time_horizon', sa.String(length=100), nullable=True))
    op.add_column('members', sa.Column('relationship', sa.String(length=50), nullable=True))
    op.add_column('members', sa.Column('city', sa.String(length=100), nullable=True))
    op.add_column('members', sa.Column('state', sa.String(length=100), nullable=True))
    op.add_column('members', sa.Column('country', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('members', 'country')
    op.drop_column('members', 'state')
    op.drop_column('members', 'city')
    op.drop_column('members', 'relationship')
    op.drop_column('households', 'time_horizon')
    op.drop_column('households', 'risk_tolerance')
    op.drop_column('households', 'expense_range')
    op.drop_column('households', 'liquid_net_worth')
    op.drop_column('bank_accounts', 'routing_number')
    op.drop_column('accounts', 'ownership_percentage')
    op.drop_column('accounts', 'ownership')
    op.drop_column('accounts', 'account_value')
    op.drop_column('accounts', 'account_number')
    # ### end Alembic commands ###
