"""added column in beneficiary

Revision ID: 9a87780eb15c
Revises: 2adfa47653d6
Create Date: 2026-03-25 09:33:43.710349

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a87780eb15c'
down_revision: Union[str, Sequence[str], None] = '2adfa47653d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('beneficiaries', sa.Column('relationship', sa.String(length=100), nullable=True))
    op.add_column('beneficiaries', sa.Column('type', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('beneficiaries', 'type')
    op.drop_column('beneficiaries', 'relationship')
    # ### end Alembic commands ###
