"""rename relationship to relation_type in members

Revision ID: a698308af38b
Revises: 9a87780eb15c
Create Date: 2026-03-25 20:47:42.551068

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'a698308af38b'
down_revision: Union[str, Sequence[str], None] = '9a87780eb15c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('members', sa.Column('relationship_type', sa.String(length=50), nullable=True))
    op.drop_column('members', 'relationship')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('members', sa.Column('relationship', mysql.VARCHAR(length=50), nullable=True))
    op.drop_column('members', 'relationship_type')
    # ### end Alembic commands ###
